platform :ios, ‘9.0’
target 'SHENCHAO’ do
pod 'AFNetworking', '~> 3.1.0'
pod 'IQKeyboardManager', '~> 4.0.9'
pod 'pop','1.0.9'
pod 'SDAutoLayout', '~> 2.1.3'
pod 'BaiduMapKit'
pod 'SDWebImage'
pod 'MJRefresh'
pod 'Masonry'
pod 'NJKWebViewProgress'
pod 'MWPhotoBrowser'              #ACMedia
pod 'TZImagePickerController'
pod 'ACAlertController'
end
